# Generated by Django 2.2 on 2022-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('books_app', '0003_book_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Rating',
            field=models.ManyToManyField(through='books_app.Review', to='login_app.User'),
        ),
    ]
