# Generated by Django 2.2 on 2022-08-05 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_app', '0006_book_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='ratings',
        ),
    ]
