# Generated by Django 2.2 on 2023-03-02 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetToken',
        ),
    ]
